services:
  postgres:
    image: postgres:18-alpine
    ports: 
    - "${postgres_port}:5432"
    environment:
      POSTGRES_USER: ${postgres_user}
      POSTGRES_PASSWORD: ${postgres_password}
      POSTGRES_DB: ${postgres_db}
    volumes:
      - postgres_data:/var/lib/postgresql
      - ./postgres/init:/docker-entrypoint-initdb.d


  redis:
    image: redis:alpine
    ports: 
    - "${redis_port}:6379"
    volumes:
      - redis_data:/data


  minio:
    image: minio/minio:latest
    ports: 
    - "${minio_port}:9000"
    - "${minio_port_alt}:9001"
    environment:
      MINIO_ROOT_USER: ${minio_user}
      MINIO_ROOT_PASSWORD: ${minio_password}
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data


  elasticsearch:
    image: elasticsearch:9.4.4
    ports: 
      - "${elasticsearch_port}:9200"
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - xpack.security.enabled=false
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    

  jaeger:
    image: jaegertracing/all-in-one:1.76.0
    ports: 
    - "${jaeger_port}:16686"
    - "${jaeger_port_alt}:4317"

  kafka:
    image: redpandadata/redpanda:v26.1.15

    ports: 
    - "${kafka_port}:9092"
    command: 
    - redpanda 
    - start
    - --kafka-addr=internal://0.0.0.0:9092
    - --advertise-kafka-addr=internal://localhost:9092
    - --smp=1
    - --mode=dev-container

    volumes:
      - kafka_data:/var/lib/redpanda/data


volumes:
  postgres_data:
  redis_data:
  minio_data:
  elasticsearch_data:
  kafka_data:
